"""empty message

Revision ID: 03d11dab1649
Revises: c07f127145ad
Create Date: 2023-11-30 01:29:08.843681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d11dab1649'
down_revision = 'c07f127145ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('birth_date')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
