"""empty message

Revision ID: a13a363b0e64
Revises: 03d11dab1649
Create Date: 2023-11-30 02:55:49.536855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13a363b0e64'
down_revision = '03d11dab1649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
